# This is a basic workflow to help you get started with Actions

name: Sync Fork

# Controls when the workflow will run
on:
  # schedule:
  #  - cron: '0 23 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # 这个 token action 会默认配置, 这里只需这样写就行
          owner: shufflewzc # fork 上游项目 owner
          head: main # fork 上游项目需要同步的分支
          base: main # 需要同步到本项目的目标分支
